# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79877073dfb64abe97582bdb5434f369155f5a17d4aa52ad34577819ede0615129fb106d6bf7ba2ad910bfb9365463949e4feafe680fef8fca9593c9e47bf381

test:
  secret_key_base: 46ac1e693c7f888a12321e581915491ef29fcbf4e5b2daae9d71f93eeb331356217799b24b5f40ae440d7fa38c2d8947b3ed888fb016cf570d5c69092a404e65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
